// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATGdulEAoQlQoUNcvoUKhKxjg291dWoXE',
    appId: '1:1041648516919:web:7268ad38020c41685124b2',
    messagingSenderId: '1041648516919',
    projectId: 'myapp-auth-fd0f9',
    authDomain: 'myapp-auth-fd0f9.firebaseapp.com',
    storageBucket: 'myapp-auth-fd0f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9S5XUVkA22g5_-s4SpPUUtvMIDVs3bwI',
    appId: '1:1041648516919:android:4584983882b9dcdc5124b2',
    messagingSenderId: '1041648516919',
    projectId: 'myapp-auth-fd0f9',
    storageBucket: 'myapp-auth-fd0f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9aV5cWWKONbyji8CpD8_uU1q0oxJ6PL0',
    appId: '1:1041648516919:ios:c18a0a478b34df125124b2',
    messagingSenderId: '1041648516919',
    projectId: 'myapp-auth-fd0f9',
    storageBucket: 'myapp-auth-fd0f9.appspot.com',
    iosBundleId: 'com.example.plantShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9aV5cWWKONbyji8CpD8_uU1q0oxJ6PL0',
    appId: '1:1041648516919:ios:c18a0a478b34df125124b2',
    messagingSenderId: '1041648516919',
    projectId: 'myapp-auth-fd0f9',
    storageBucket: 'myapp-auth-fd0f9.appspot.com',
    iosBundleId: 'com.example.plantShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATGdulEAoQlQoUNcvoUKhKxjg291dWoXE',
    appId: '1:1041648516919:web:a23f9bcda72907fa5124b2',
    messagingSenderId: '1041648516919',
    projectId: 'myapp-auth-fd0f9',
    authDomain: 'myapp-auth-fd0f9.firebaseapp.com',
    storageBucket: 'myapp-auth-fd0f9.appspot.com',
  );
}
